input_dir: ${PROJECT_DIR}/SwiftGenDemo
output_dir: ${PROJECT_DIR}/SwiftGenDemo/SwiftGen
xcassets:
  inputs:
    - Assets.xcassets
    - Colors.xcassets
  outputs:
    - templatePath: ${PROJECT_DIR}/SwiftGenDemo/SwiftGen/template.stencil
      params:
        publicAccess: true
      output: Assets.generated.swift

 
