
#  swiftgen config run --config SwiftGenDemo/SwiftGen/swiftgen.color.config.yml

input_dir: ${PROJECT_DIR}/SwiftGenDemo
output_dir: ${PROJECT_DIR}/SwiftGenDemo/SwiftGen
xcassets:
  inputs:
    - Colors.xcassets
  outputs:
    - templatePath: ${PROJECT_DIR}/SwiftGenDemo/SwiftGen/colorTemplate.stencil
      params:
        publicAccess: true
      output: color.generated.swift

