
#  swiftgen config run --config SwiftGenDemo/SwiftGen/swiftgen.image.config.yml

input_dir: ${PROJECT_DIR}/SwiftGenDemo
output_dir: ${PROJECT_DIR}/SwiftGenDemo/SwiftGen
xcassets:
  inputs:
    - Images.xcassets
  outputs:
    - templatePath: ${PROJECT_DIR}/SwiftGenDemo/SwiftGen/imageTemplate.stencil
      params:
        publicAccess: true
      output: image.generated.swift
